// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PCSafImD913mzwUIl0XaK5Mg9gsUwvk',
    appId: '1:383672805457:web:21a407decf288cf6b13070',
    messagingSenderId: '383672805457',
    projectId: 'foreverfusion-e883e',
    authDomain: 'foreverfusion-e883e.firebaseapp.com',
    storageBucket: 'foreverfusion-e883e.firebasestorage.app',
    measurementId: 'G-HNX4F77VFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMT9JBOL0NpVbYrpGW09-NhZCD5aDmTE',
    appId: '1:383672805457:android:3e1bf0dea037b66bb13070',
    messagingSenderId: '383672805457',
    projectId: 'foreverfusion-e883e',
    storageBucket: 'foreverfusion-e883e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpF7vSSjkHhbVBYXUPezBLajZQd-p1DHc',
    appId: '1:383672805457:ios:a6c868ca0668d496b13070',
    messagingSenderId: '383672805457',
    projectId: 'foreverfusion-e883e',
    storageBucket: 'foreverfusion-e883e.firebasestorage.app',
    iosBundleId: 'com.example.foreverFusion',
  );
}
